version: '3.8'

services:
  # 1. ส่วนของ Backend (App ของเรา)
  backend:
    build: ./backend     # สร้างจาก Dockerfile ที่คุณมีอยู่
    ports:
      - "3000:3000"      # เปิด Port 3000 ให้หน้าเว็บคุยได้
    environment:
      - DB_HOST=db       # บอกให้วิ่งไปหา Database ชื่อ db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SEED_USER_EMAIL=${SEED_USER_EMAIL}
      - SEED_USER_PASSWORD=${SEED_USER_PASSWORD}
    depends_on:
      - db               # รอให้ Database รันเสร็จก่อนค่อยรัน App
    networks:
      - app-network

  # 2. ส่วนของ Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: